spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: secret_key_for_testing_purposes_only_must_be_changed_in_prod_1234567890
  expiration: 86400000 # 24 hours
