spring:
  application:
    name: gateway-service
  threads:
    virtual:
      enabled: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  
  data:
    redis:
      host: localhost
      port: 6379

grpc:
  server:
    port: 9090
